# Generated by Django 3.1.3 on 2020-11-10 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Krysten', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
