# Generated by Django 3.1.3 on 2020-11-10 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Krysten', '0002_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Description',
        ),
        migrations.AlterField(
            model_name='person',
            name='image_url',
            field=models.ImageField(upload_to=''),
        ),
    ]
