# Generated by Django 3.1.3 on 2020-11-10 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Krysten', '0003_auto_20201110_0229'),
    ]

    operations = [
        migrations.CreateModel(
            name='Texts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('poem_pdf', models.FileField(upload_to='poems/')),
            ],
        ),
    ]
