# Generated by Django 3.1.3 on 2020-11-10 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Krysten', '0004_texts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('content_url', models.TextField()),
            ],
        ),
    ]
